### PR TITLE
Offline read status notification with LEDs

### PR DESCRIPTION
**Pull request by nemanjan00**
Fix for #81

### CODE REVIEW

**Comment by doegox** [comment]
From a dual LF/HF slot, after searching (without tag), slot LED end up on blue instead of red.

**Comment by nemanjan00** [comment]
I do not have blue hard-coded anywhere, so I have no idea what is happening

**Comment by nemanjan00** [comment]
I can confirm the same thing is happening to me

**Comment by doegox** [comment]
Blue led fixed in 7ed8005

**Pull request merged**
