### PR TITLE
Adding Authorized Distributors TechSecurityTools

### PR DESCRIPTION
**Pull request by yanis333**

### CODE REVIEW

**Comment by GameTec-live** [comment]
are they really an authorized distributor?

**Comment by xianglin1998** [comment]
> are they really an authorized distributor?

I need to ask Dot.com.

**Comment by yanis333** [comment]
Do you know how to become an official authorized distributor? I don't find the link or form

**Comment by GameTec-live** [comment]
you talk to RRG

**Comment by yanis333** [comment]
I tried to send them a message via the Contact Us in this website : https://rfidresearchgroup.com/

They did not ansmer me. Is there an another way to contact them ?

Thanks for your help !

**Comment by GameTec-live** [comment]
@xianglin1998

**Comment by xianglin1998** [comment]
Confirmed with RRG.

**Pull request merged**
