### PR TITLE
Update MTools BLE documentation

### PR DESCRIPTION
**Pull request by whywilson**
@xianglin1998

### CODE REVIEW

**Comment by GameTec-live** [comment]
why just make a new pr, you can edit existing ones lol
Also, i still doubt that your a official reseller...

**Comment by whywilson** [comment]
The intro for the CU GUI remains the same. So pr again. 
And RRG will judge on this.

**Comment by GameTec-live** [comment]
"And RRG will judge on this"
Yeah, but as authorised resellers have to be approved by rrg and that was done when the CU launched, i feel if you were authorised youd already be on this list and also not sell clones lol

**Comment by xianglin1998** [comment]
> "And RRG will judge on this" Yeah, but as authorised resellers have to be approved by rrg and that was done when the CU launched, i feel if you were authorised youd already be on this list and also not sell clones lol

After my confirmation, RRG has authorized mtoolstec.

**Pull request merged**
