### PR TITLE
doc: Add box net and vectortraced boxart and troubleshooting entry

### PR DESCRIPTION
**Pull request by GameTec-live**
As someone in the discord wanted a SVG of the boxart and none are publicly avialable, i decided to scan in my boxes and vectortrace them in inkscape. Altough the "official" files would be preferrable, those traces turned out pretty well id say...
Also added boxnets for completness sake / the box scans....

Also adds a entry to the troubleshooting guide and a python version notice

### CODE REVIEW

**Comment by xianglin1998** [comment]
It's too big, which can cause slow cloning in some areas with poor network performance. I suggest compressing high-definition image resources into zip files for stored. The quality of the preview images can be appropriately reduced.

**Comment by GameTec-live** [comment]
@xianglin1998 Compressed them into a zip...

**Comment by doegox** [comment]
Note to ourselves: we need to squash this PR when merged, else we'll end up with the large ones in the repo history anyway

**Comment by xianglin1998** [comment]
> Note to ourselves: we need to squash this PR when merged, else we'll end up with the large ones in the repo history anyway
image
This item?

**Pull request merged**
