### PR TITLE
This *should* autodedect the chameleons port if none is supplied

### PR DESCRIPTION
**Pull request by GameTec-live**
This _should_ autodedect the chameleons port (in hw connect) if none is supplied, has to be tested though, cant do it myself, because i dont own the hardware _yet_.

### CODE REVIEW

**Comment by xianglin1998** [comment]
I have manually merged your PRs, and I suggest "One PR for One Action".

**Comment by GameTec-live** [comment]
> I have manually merged your PRs, and I suggest "One PR for One Action".

ok, thx, altough unsure what you mean by "One PR for One Action".

**Comment by xianglin1998** [comment]
> > I have manually merged your PRs, and I suggest "One PR for One Action".
> 
> ok, thx, altough unsure what you mean by "One PR for One Action".

HaHa. The meaning is that PR only solves one problem at a time.

**Comment by GameTec-live** [comment]
> > > I have manually merged your PRs, and I suggest "One PR for One Action".
> > 
> > 
> > ok, thx, altough unsure what you mean by "One PR for One Action".
> 
> HaHa. The meaning is that PR only solves one problem at a time.

you cant fix a script error if the gitignore ignores the scripts XD

**Pull request closed without merging**
